module.exports = {
	SESSION_STATE : {
		SESSION_NEED_CLEAR : 0,
		SESSION_STATE_READY : 1,
		SESSION_STATE_CLIENT_END : 2
	},
	CONN_PLAYER_STATE : {
		IDLE : 0,
		READY_FOR_CLIENT : 1,
		CLIENT_CONNECTED : 2,
		NEED_KICK_OUT : 3
	}
};
